driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: boilerplate
    run_list:
      - recipe[chef-dk]
      - recipe[boilerplate]
