name 'boilerplate'
maintainer 'topaz2'
maintainer_email 'topaz2@m0n0m0n0.com'
license 'GPL v3'
description 'Installs/Configures boilerplate'
version '0.3.1'

depends 'node'
depends 'nodejs'
depends 'apt-repo'
depends 'apache2'
depends 'database'
depends 'mysql'
depends 'jenkins'
depends 'ruby'
depends 'gitlab'
