name 'boilerplate'
maintainer 'topaz2'
maintainer_email 'topaz2@m0n0m0n0.com'
license 'GPL v3'
description 'Installs/Configures boilerplate'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.3.6'

depends 'node'
depends 'nodejs'
depends 'phantomjs'
depends 'apt-repo'
depends 'apache2'
depends 'database'
depends 'mysql'
depends 'jenkins'
depends 'ruby'
depends 'gitlab'
